/// Flutter icons ServicesIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ServicesIcons
///      fonts:
///       - asset: fonts/ServicesIcons.ttf
///
///
///
import 'package:flutter/widgets.dart';

class ServicesIcons {
  ServicesIcons._();

  static const _kFontFam = 'ServicesIcons';
  static const String? _kFontPkg = null;

  static const IconData face_mask =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hair_dye =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scissors =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wax =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData nail_polish =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
